---
- hosts: QA_hosts
  tasks:
  - name: Log into Nexus
    docker_login:
#      docker_host: unix://run/containerd/containerd.sock
      registry: 172.31.40.122:8082
      username: upload
      password: GrurAv0Wrooc
  - name: Get a list of all running containers
    docker_host_info:
      containers: yes
    register: docker_info
  - name: Stop all running containers
    docker_container:
      name: '{{ item.Names[0] | regex_replace("^/", "") }}'
      state: stopped
    loop: '{{ docker_info.containers }}'
  - name: Create JAVA_APP container on DEV
    docker_container:
      name: "grw_{{ build_Number }}"
      image: "{{ src_image }}"
      ports:
        - "{{ port_number }}:8080/tcp"
  - name: Create JAVA_APP container on QA
    docker_container:
      name: "grw_{{ build_Number }}"
      image: "{{ src_image }}"
      ports:
        - "{{ port_number }}:8080/tcp"
  - name: Log out of Nexus
    docker_login:
      state: absent
